=== dougmencken/HeadOverHeels/gamedata/map/room.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="room" type="RoomXML"/>
  <xsd:complexType name="RoomXML">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="scenery" type="xsd:string"/>
      <xsd:element name="xTiles" type="xsd:int"/>
      <xsd:element name="yTiles" type="xsd:int"/>
      <xsd:element name="width" type="xsd:int"/>
      <xsd:element name="floorType" type="xsd:string"/>
      <xsd:element name="deltaX" type="xsd:int" minOccurs="0"/>
      <xsd:element name="deltaY" type="xsd:int" minOccurs="0"/>
      <xsd:element name="triple-room-data" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="northeast" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="southeast" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="northwest" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="southwest" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="eastnorth" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="eastsouth" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="westnorth" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="westsouth" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="bound-x">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="minimum" type="xsd:int"/>
                  <xsd:element name="maximum" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="bound-y">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="minimum" type="xsd:int"/>
                  <xsd:element name="maximum" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="floor">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="tile" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                  <xsd:element name="offsetX" type="xsd:int"/>
                  <xsd:element name="offsetY" type="xsd:int"/>
                  <xsd:element name="picture" type="xsd:string"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="walls" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="wall" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="axis">
                    <xsd:simpleType>
                      <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="x"/>
                        <xsd:enumeration value="y"/>
                      </xsd:restriction>
                    </xsd:simpleType>
                  </xsd:element>
                  <xsd:element name="index" type="xsd:int"/>
                  <xsd:element name="picture" type="xsd:string"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="items">
        <xsd:complexType>
          <xsd:sequence>
          <xsd:element name="item" maxOccurs="unbounded">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="label" type="xsd:short"/>
                <xsd:element name="direction">
                  <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                      <xsd:enumeration value="none"/>
                      <xsd:enumeration value="south"/>
                      <xsd:enumeration value="west"/>
                      <xsd:enumeration value="north"/>
                      <xsd:enumeration value="east"/>
                      <xsd:enumeration value="northeast"/>
                      <xsd:enumeration value="southeast"/>
                      <xsd:enumeration value="southwest"/>
                      <xsd:enumeration value="northwest"/>
                      <xsd:enumeration value="eastnorth"/>
                      <xsd:enumeration value="eastsouth"/>
                      <xsd:enumeration value="westnorth"/>
                      <xsd:enumeration value="westsouth"/>
                    </xsd:restriction>
                  </xsd:simpleType>
                </xsd:element>
                <xsd:element name="behavior" type="xsd:string"/>
                <xsd:element name="type">
                  <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                      <xsd:enumeration value="wall"/>
                      <xsd:enumeration value="door"/>
                      <xsd:enumeration value="griditem"/>
                      <xsd:enumeration value="freeitem"/>
                    </xsd:restriction>
                  </xsd:simpleType>
                </xsd:element>
                <xsd:element name="extra" type="xsd:int" minOccurs="0" maxOccurs="unbounded"/>
              </xsd:sequence>
              <xsd:attribute name="x" type="xsd:int" use="required"/>
              <xsd:attribute name="y" type="xsd:int" use="required"/>
              <xsd:attribute name="z" type="xsd:int" use="required"/>
            </xsd:complexType>
          </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== dougmencken/HeadOverHeels/gamedata/map/blacktooth/blacktooth05.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<room xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="room.xsd">

  <name>blacktooth/blacktooth05.xml</name>

  <scenery>blacktooth</scenery>

  <xTiles>3</xTiles>

  <yTiles>10</yTiles>

  <width>16</width>

  <floorType>regular</floorType>

  <floor>
    <tile>
      <x>0</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor-north.png</bitmap>
    </tile>
    <tile>
      <x>0</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor-north.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor-east.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor-east.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>9</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor-west.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>9</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor-west.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>7</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>8</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>7</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>8</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/blacktooth.png/blacktooth-floor.png</bitmap>
    </tile>
  </floor>

  <items>
    <item x="0" y="1" z="0">
      <label>211</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="2" z="0">
      <label>213</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="3" z="0">
      <label>211</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="6" z="0">
      <label>211</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="7" z="0">
      <label>213</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="8" z="0">
      <label>211</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="4" z="-1">
      <label>2011</label>
      <direction>north</direction>
      <behavior>0</behavior>
      <type>door</type>
    </item>
    <item x="1" y="0" z="-1">
      <label>5011</label>
      <direction>east</direction>
      <behavior>0</behavior>
      <type>door</type>
    </item>
    <item x="1" y="9" z="-1">
      <label>5011</label>
      <direction>west</direction>
      <behavior>0</behavior>
      <type>door</type>
    </item>
    <item x="1" y="6" z="0">
      <label>4</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="2" y="6" z="0">
      <label>4</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
  </items>

</room>

=== dougmencken/HeadOverHeels/gamedata/map/safari/safari08.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<room xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="room.xsd">

  <name>safari/safari08.xml</name>

  <scenery>safari</scenery>

  <xTiles>10</xTiles>

  <yTiles>2</yTiles>

  <width>16</width>

  <floorType>regular</floorType>

  <floor>
    <tile>
      <x>0</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor-north.png</bitmap>
    </tile>
    <tile>
      <x>0</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor-north.png</bitmap>
    </tile>
    <tile>
      <x>9</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor-south.png</bitmap>
    </tile>
    <tile>
      <x>9</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor-south.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>7</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>7</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>8</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
    <tile>
      <x>8</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari.png/safari-floor.png</bitmap>
    </tile>
  </floor>

  <walls>
    <wall>
      <axis>x</axis>
      <index>1</index>
      <bitmap>gfx/safari.png/safari-wall-x-1.png</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>2</index>
      <bitmap>gfx/safari.png/safari-wall-x-3.png</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>3</index>
      <bitmap>gfx/safari.png/safari-wall-x-1.png</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>4</index>
      <bitmap>gfx/safari.png/safari-wall-x-2.png</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>5</index>
      <bitmap>gfx/safari.png/safari-wall-x-2.png</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>6</index>
      <bitmap>gfx/safari.png/safari-wall-x-1.png</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>7</index>
      <bitmap>gfx/safari.png/safari-wall-x-3.png</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>8</index>
      <bitmap>gfx/safari.png/safari-wall-x-1.png</bitmap>
    </wall>
  </walls>

  <items>
    <item x="0" y="0" z="-1">
      <label>307</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="1" z="-1">
      <label>307</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="0" z="-1">
      <label>3077</label>
      <direction>north</direction>
      <behavior>0</behavior>
      <type>door</type>
    </item>
    <item x="9" y="0" z="0">
      <label>310</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="9" y="1" z="0">
      <label>310</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="9" y="0" z="-1">
      <label>3077</label>
      <direction>south</direction>
      <behavior>0</behavior>
      <type>door</type>
    </item>
  </items>

</room>
